const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const root=path.resolve(__dirname,'..'),workbench=process.env.WORKBENCH_PATH;
if(!workbench)throw Error('Set WORKBENCH_PATH to the updated workbench JavaScript.');
function wav(seconds,level,sine=false){const n=Math.round(seconds*8000),b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)b.writeInt16LE(Math.round(32767*level*(sine?Math.sin(i/8000*2*Math.PI*220):1)),44+i*2);return b;}
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:420,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('http://tavern.test/**',r=>r.fulfill({contentType:'text/html; charset=utf-8',body:'<style>:root{--SmartThemeBodyColor:#e5e2df;--SmartThemeBlurTintColor:#23262b;--SmartThemeChatTintColor:#181b20;--SmartThemeBorderColor:#555860;--SmartThemeQuoteColor:#d9b7da}body{background:#181b20;color:#e5e2df;font:16px/2 sans-serif;padding:18px}.mes_text{padding:15px;border:1px solid #555;border-radius:14px;margin-top:25px}</style><div id="top-bar"></div><div id="extensionsMenu"></div><div id="chat"><div class="mes" mesid="0"><div class="mes_text"><p>你好梨梨。</p><p>晚安梨梨。</p></div></div></div><textarea id="send_textarea"></textarea>'}));
await page.route('https://s1.oururl.cn/**',r=>r.fulfill({status:404,body:''}));let calls=0;const chunks=[wav(2,.1),wav(3,.3)];await page.route('https://api.minimaxi.com/**',r=>r.fulfill({contentType:'audio/wav',body:chunks[calls++%2]}));await page.goto('http://tavern.test');await page.evaluate(()=>{window.SillyTavern={getContext:()=>({chatId:'test',characterId:0,characters:[{avatar:'test.png'}],chat:[{mes:'你好梨梨。\n晚安梨梨。',send_date:'test',name:'角色',swipe_id:0}],extensionSettings:{},eventSource:{on(){},removeListener(){}},eventTypes:{}})};});
await page.evaluate(()=>localStorage.setItem('lili-minimax-voice-v1',JSON.stringify({selected:'a',voices:[{id:'a',name:'角色 A',voiceId:'voice-a',speed:1,volume:1,pitch:0},{id:'b',name:'角色 B',voiceId:'voice-b',speed:1,volume:1,pitch:0}]})));await page.addStyleTag({path:path.join(root,'style.css')});await page.addScriptTag({path:path.join(root,'index.js')});const $=id=>page.locator(`[data-id=${id}]`);
async function select(i){await page.locator('.mes_text p').nth(i).evaluate(el=>{const r=document.createRange();r.selectNodeContents(el);const sel=getSelection();sel.removeAllRanges();sel.addRange(r);});await page.locator('#lv-selection').click();}

await page.locator('#lv-menu').click();await $('tabConfig').click();await $('key').fill('mock-key');await $('saveConfig').click();await page.waitForFunction(()=>!document.querySelector('[data-id=saveConfig]').disabled);await $('tabRead').click();await $('batchBox').evaluate(e=>e.open=true);await page.getByRole('textbox',{name:'第 1 段台词',exact:true}).fill('A 的台词');await $('batchAdd').click();await page.getByLabel('第 2 段音色',{exact:true}).selectOption('b');await page.getByRole('textbox',{name:'第 2 段台词',exact:true}).fill('B 的台词');
let attempts=0;await page.unroute('https://api.minimaxi.com/**');await page.route('https://api.minimaxi.com/**',r=>{attempts++;const body=r.request().postDataJSON();if(attempts===2)return r.fulfill({status:500,contentType:'application/json',body:JSON.stringify({base_resp:{status_code:1000,status_msg:'mock temporary failure'}})});return r.fulfill({contentType:'audio/wav',body:body.voice_setting.voice_id==='voice-a'?chunks[0]:chunks[1]});});
await $('batchMake').click();await page.waitForFunction(()=>document.querySelector('[data-id=batchStatus]').textContent.includes('未完成'));assert.equal(attempts,2);await $('batchMake').click();await page.waitForFunction(()=>document.querySelector('#lv-status').textContent.includes('多角色对话已保存'));assert.equal(attempts,3,'completed A must be reused');await page.waitForFunction(()=>document.querySelectorAll('[data-id=historyList] details').length===1);
const result=await page.evaluate(async()=>{const db=await new Promise(res=>{const r=indexedDB.open('lili-voice-history',2);r.onsuccess=()=>res(r.result);});const rows=await new Promise(res=>{const r=db.transaction('records').objectStore('records').getAll();r.onsuccess=()=>res(r.result);});db.close();return rows.map(r=>({id:r.id,text:r.text,mix:r.mix}));});assert.equal(result.length,3);assert.equal(result.find(r=>r.mix).mix.parts.length,2);
await $('historyList').locator('summary').click();await page.getByRole('button',{name:'拆开大配音',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('[data-id=historyList] details').length===2);
for(const checkbox of await $('historyList').locator('input[type=checkbox]').all())await checkbox.check();await $('mixSelected').click();await page.getByRole('button',{name:'调整录音 2 ↑',exact:true}).click();await page.locator('[data-id=mixGap]').evaluate(e=>e.closest('details').open=true);await page.locator('[data-id=mixGap]').fill('0.25');await page.locator('[data-id=mixBgm]').setInputFiles({name:'bgm.wav',mimeType:'audio/wav',buffer:wav(.5,.1,true)});await $('mixMake').click();await page.waitForFunction(()=>document.querySelector('#lv-status').textContent.includes('大配音已保存'));assert.equal(attempts,3,'combining recordings must not call synthesis');assert.equal(await $('historyList').locator('details').count(),1);assert.deepEqual(errors,[]);await browser.close();console.log('PASS: multi-role batch, partial failure and cached resume, real combined WAV, split, reorder existing recordings, BGM, local merge without API calls.');
})().catch(e=>{console.error(e);process.exit(1)});
