const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');const source=fs.readFileSync(require('node:path').join(__dirname,'../index.js'),'utf8'),lines=source.split('\n');const elements=new Map(),handlers=new Map(),calls=[],events=[];const $=id=>{if(!elements.has(id))elements.set(id,{id,value:''});return elements.get(id);};let response=()=>new Response(Uint8Array.from([73,68,51]),{headers:{'content-type':'audio/mpeg'}});
const W={location:{origin:'http://localhost:8000'},SillyTavern:{getContext:()=>({getRequestHeaders:()=>({'X-CSRF-Token':'token'})})},fetch:async(url,options)=>{calls.push({url,options});return response();},Event:class{constructor(type){this.type=type;}},dispatchEvent:e=>events.push(e.type)};
const config={provider:'minimax',elevenlabs:{host:'https://api.elevenlabs.io',model:'eleven_multilingual_v2',stability:.5,similarity:.75,transport:'auto'}};
const c=vm.createContext({W,URL,Response,Uint8Array,TextDecoder,AbortController,setTimeout,clearTimeout,tasks:new Set(),Object,JSON,Error,Number,Math,String,structuredClone,config,apiProfiles:{mini:[],sub:[]},$,on:(el,e,fn)=>handlers.set(el.id,fn),profileAction:fn=>fn(),persistProfiles:async next=>{c.apiProfiles=next;},store(){},drawBatch(){},clearInlineCache(){},status(){},safe:s=>String(s).replaceAll('eleven-key','[hidden]')});
for(const name of ['normalizeElevenHost','fillElevenProfile','effectiveVoice','readConfig','cleanKey','activateProvider','fishRequestRoute','fishBridgePayload','isMp3Response','request','elevenRaw'])vm.runInContext(lines.find(l=>l.startsWith((['request','elevenRaw'].includes(name)?'async ':'')+'function '+name+'(')),c);
vm.runInContext(lines.find(l=>l.startsWith("on($('saveEleven'),'click'")),c);
const body={text:'(sighs)你好<#0.5#>梨梨',voice_setting:{voice_id:'voice-eleven',speed:1,vol:1,pitch:0}};
(async()=>{
 Object.assign($('elevenHost'),{value:'https://api.elevenlabs.io/v1/'});$('elevenModel').value='eleven_multilingual_v2';$('elevenKey').value='eleven-key';$('elevenStability').value='.5';$('elevenSimilarity').value='.75';$('elevenTransport').value='auto';await handlers.get('saveEleven')();assert.equal(config.provider,'elevenlabs');assert.equal(c.apiProfiles.elevenlabs.key,'eleven-key');assert.equal(config.elevenlabs.key,undefined,'key stays in API vault');assert(events.includes('li-voice-studio:change'));assert.equal(c.cleanKey('elevenlabs'),'eleven-key');assert.equal(c.effectiveVoice({voiceId:'mini',fishVoiceId:'fish',elevenVoiceId:'eleven'},'elevenlabs').voiceId,'eleven');assert.equal(c.readConfig('elevenlabs').model,'eleven_multilingual_v2');
 let result=await c.elevenRaw({...config.elevenlabs,provider:'elevenlabs',elevenlabs:config.elevenlabs},body,'eleven-key');assert.equal(result.type,'audio/mpeg');assert.equal(calls.length,1);let sent=JSON.parse(calls[0].options.body);assert.equal(calls[0].options.headers['xi-api-key'],'eleven-key');assert.equal(calls[0].options.headers.Authorization,undefined);assert.equal(calls[0].options.credentials,'omit');const target=new URL(calls[0].url);assert.equal(target.origin,'https://api.elevenlabs.io');assert.equal(target.pathname,'/v1/text-to-speech/voice-eleven');assert.equal(target.searchParams.get('output_format'),'mp3_44100_128');assert.equal(sent.model_id,'eleven_multilingual_v2');assert.equal(sent.text,'你好<break time="0.5s" />梨梨');assert.equal(sent.voice_settings.speed,1);assert.equal(config.provider,'elevenlabs');
 calls.length=0;await c.elevenRaw({provider:'elevenlabs',host:'https://api.elevenlabs.io',model:'eleven_v3',elevenlabs:{transport:'direct'}},body,'eleven-key');assert.equal(calls[0].options.headers['xi-api-key'],'eleven-key');assert.equal(calls[0].options.headers.Authorization,undefined);sent=JSON.parse(calls[0].options.body);assert.equal(sent.text,'[sighs]你好[short pause]梨梨');
 calls.length=0;await assert.rejects(c.elevenRaw({...config.elevenlabs}, {...body,voice_setting:{...body.voice_setting,speed:1.5}},'eleven-key'),/0.7/);assert.equal(calls.length,0);
 response=()=>Response.json({detail:{status:'quota_exceeded',message:'额度不足 eleven-key'}},{status:401});await assert.rejects(c.elevenRaw({...config.elevenlabs},body,'eleven-key'),/额度不足 \[hidden\]/);assert.equal(calls.length,1,'no automatic synthesis retries');assert.equal(c.tasks.size,0);
 assert(source.includes("prepend(elevenPanel);$('configPage').prepend(miniPanel)"));assert(source.includes("['minimax','MiniMax'],['elevenlabs','ElevenLabs'],['fish'"));console.log('PASS ElevenLabs vault save/activation, provider isolation, xi-api-key-only auto/direct auth, exact TTS path/query, MP3, model tag conversion, speed preflight, error redaction and no retries');
})().catch(e=>{console.error(e);process.exitCode=1;});
