const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const root=path.resolve(__dirname,'..'),workbench=process.env.WORKBENCH_PATH;
if(!workbench)throw Error('Set WORKBENCH_PATH to the updated workbench JavaScript.');
function wav(seconds,level,sine=false){const n=Math.round(seconds*8000),b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)b.writeInt16LE(Math.round(32767*level*(sine?Math.sin(i/8000*2*Math.PI*220):1)),44+i*2);return b;}
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:420,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('http://tavern.test/**',r=>r.fulfill({contentType:'text/html; charset=utf-8',body:'<style>:root{--SmartThemeBodyColor:#e5e2df;--SmartThemeBlurTintColor:#23262b;--SmartThemeChatTintColor:#181b20;--SmartThemeBorderColor:#555860;--SmartThemeQuoteColor:#d9b7da}body{background:#181b20;color:#e5e2df;font:16px/2 sans-serif;padding:18px}.mes_text{padding:15px;border:1px solid #555;border-radius:14px;margin-top:25px}</style><div id="top-bar"></div><div id="extensionsMenu"></div><div id="chat"><div class="mes" mesid="0"><div class="mes_text"><p>你好梨梨。</p><p>晚安梨梨。</p></div></div></div><textarea id="send_textarea"></textarea>'}));
await page.route('https://s1.oururl.cn/**',r=>r.fulfill({status:404,body:''}));let calls=0;const chunks=[wav(2,.1),wav(3,.3)];await page.route('https://api.minimaxi.com/**',r=>r.fulfill({contentType:'audio/wav',body:chunks[calls++]}));await page.goto('http://tavern.test');await page.evaluate(()=>{window.SillyTavern={getContext:()=>({chatId:'test',characterId:0,characters:[{avatar:'test.png'}],chat:[{mes:'你好梨梨。\n晚安梨梨。',send_date:'test',name:'角色',swipe_id:0}],extensionSettings:{},eventSource:{on(){},removeListener(){}},eventTypes:{}})};});
await page.evaluate(()=>{const settings={regex:[{id:'r1',scriptName:'正则一',findRegex:'a',replaceString:'b',disabled:false}],tavern_helper:{script:{scripts:[{type:'script',id:'s1',name:'脚本一',content:'console.log(1)',enabled:false}]}}};window.SillyTavern.getContext=()=>({extensionSettings:settings,characters:[],chat:[]});});
await page.route('http://tavern.test/api/extensions/discover',r=>r.fulfill({contentType:'application/json',body:JSON.stringify([{name:'aaa',type:'system'},{name:'bbb',type:'system'}])}));await page.route('http://tavern.test/scripts/extensions/**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({display_name:r.request().url().includes('/aaa/')?'AAA':'BBB'})}));await page.addScriptTag({path:workbench});await page.locator('#cw-fab').click();await page.locator('[data-tab=tools]').click();
async function group(name){await page.getByRole('button',{name:'新建分组',exact:true}).click();await page.locator('dialog.cw-dialog input').fill(name);await page.locator('dialog.cw-dialog button').last().click();await page.getByLabel('条目分组',{exact:true}).selectOption('*');await page.getByLabel('条目所属分组',{exact:true}).selectOption(name);assert.equal(await page.locator('.tl-group').count(),1);}
await group('正则组');await page.locator('[data-kind=script]').click();await page.getByRole('button',{name:'▸ 脚本一',exact:true}).waitFor();await group('脚本组');await page.locator('[data-kind=plugin]').click();await page.getByText('AAA',{exact:true}).waitFor();await page.locator('.tl-list button').filter({hasText:'↓'}).first().click();const config=await page.evaluate(()=>JSON.parse(localStorage.getItem('cyll-pear-hub-v1')));assert.equal(config.pluginOrder[0],'bbb');assert.equal(config.toolGroups['["regex","global",""]'].assignments.r1,'正则组');assert.equal(config.toolGroups['["script","global",""]'].assignments.s1,'脚本组');await page.addScriptTag({path:workbench});await page.locator('#cw-fab').click();await page.locator('[data-tab=tools]').click();await page.getByText('BBB',{exact:true}).waitFor();assert.match(await page.locator('.tl-list').textContent(),/BBB.*AAA/);assert.deepEqual(errors,[]);await browser.close();console.log('PASS: separate script/regex groups and custom plugin order survive workbench restart.');
})().catch(e=>{console.error(e);process.exit(1)});
