(() => {
  const pending=new Map();let serial=0;
  window.__pearNativeResult=(id,result)=>{const job=pending.get(id);if(!job)return;pending.delete(id);job.cleanup?.();if(result.error)job.reject(new Error(result.error));else job.resolve(result);};
  function call(method,payload,signal){return new Promise((resolve,reject)=>{if(signal?.aborted){reject(new DOMException('Aborted','AbortError'));return;}const id=String(++serial),abort=()=>{pending.delete(id);window.PearAndroid.cancel(id);reject(new DOMException('Aborted','AbortError'));};pending.set(id,{resolve,reject,cleanup:()=>signal?.removeEventListener('abort',abort)});signal?.addEventListener('abort',abort,{once:true});try{window.PearAndroid[method](id,JSON.stringify(payload));}catch(err){pending.delete(id);signal?.removeEventListener('abort',abort);reject(err);}});}
  window.pearFetch=async(url,options={})=>{if(window.__pearDesktopNonce){return fetch('/desktop/request',{method:'POST',headers:{'Content-Type':'application/json','X-Pear-Nonce':window.__pearDesktopNonce},body:JSON.stringify({url,method:options.method||'GET',headers:options.headers||{},body:options.body||''}),signal:options.signal}).then(async response=>{if(response.headers.get('X-Pear-Error'))throw Error(await response.text());return response;});}if(!window.PearAndroid){const target=new URL(url,location.href);const endpoint=target.origin==='https://image.novelai.net'?'/nai'+target.pathname:target.href;return fetch(endpoint,options);}const data=await call('request',{url,method:options.method||'GET',headers:options.headers||{},body:options.body||''},options.signal);const bytes=Uint8Array.from(atob(data.body||''),c=>c.charCodeAt(0));return new Response(bytes,{status:data.status,headers:{'content-type':data.contentType||'application/octet-stream'}});};
  window.pearSaveBlob=async(blob,name)=>{const base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(Error('读取文件失败'));r.readAsDataURL(blob);});if(window.__pearDesktopNonce){const r=await fetch('/desktop/save',{method:'POST',headers:{'Content-Type':'application/json','X-Pear-Nonce':window.__pearDesktopNonce},body:JSON.stringify({name,data:base64})});if(!r.ok)throw Error(await r.text());return r.json();}await call('save',{name,mime:blob.type||'application/octet-stream',data:base64});};
  window.pearSave=async(url,name)=>{const blob=await(await fetch(url)).blob();return window.pearSaveBlob(blob,name);};
  window.addEventListener('error',event=>{const startup=document.getElementById('startup');if(startup)startup.textContent='配音室未能打开：'+event.message+'。请使用较新的浏览器 / Android System WebView。';});
})();

