(() => {
 'use strict';
 const boot=async()=>{
 const core=window.PearVoiceCore;if(!core)return;
 await core.ready;
 const dialog=document.getElementById('lv-dialog'),q=id=>dialog.querySelector(`[data-id="${id}"]`),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
 const balance=el('button','余额 · 登录','lv-balance');balance.type='button';balance.dataset.id='balance';balance.title='官网余额与消费明细';dialog.querySelector('.lv-head').append(balance);
 const page=el('section');page.className='lv-page lv-workbench';page.dataset.id='workbenchPage';page.id='lv-page-workbench';page.hidden=true;page.setAttribute('role','tabpanel');page.setAttribute('aria-labelledby','lv-tab-workbench');
 page.innerHTML=`<h3>克隆工作台</h3><p data-id="workProfile"></p><div class="lv-row lv-work-tabs" role="tablist" aria-label="音色创作方式"><button type="button" data-id="modeClone" role="tab" aria-selected="true">上传音频克隆</button><button type="button" data-id="modeDesign" role="tab" aria-selected="false">文字生成音色</button></div><label>音色名称<input data-id="workName" maxlength="80" placeholder="给新声音起个名字"></label><label>Voice ID<input data-id="workVoiceId" maxlength="256" placeholder="留空自动生成"></label><div data-id="cloneFields"><label>参考音频<input data-id="cloneFile" type="file" accept=".mp3,.m4a,.wav,audio/mpeg,audio/mp4,audio/wav"></label><p>MP3 / M4A / WAV · 10 秒–5 分钟 · 不超过 20 MB</p><audio data-id="sampleAudio" controls hidden></audio><details><summary>克隆细节</summary><label class="lv-check"><input data-id="denoise" type="checkbox">降噪</label><label class="lv-check"><input data-id="normalize" type="checkbox">音量归一化</label><label>辅助音频（可选，小于 8 秒）<input data-id="promptFile" type="file" accept=".mp3,.m4a,.wav"></label><label>辅助音频原文<textarea data-id="promptText" maxlength="1000" placeholder="逐字填写辅助音频说的内容"></textarea></label></details></div><div data-id="designFields" hidden><label>声音描述<textarea data-id="voiceDescription" maxlength="5000" placeholder="例如：温柔的青年男声，音色清亮，语气自然，带一点笑意。"></textarea></label></div><label>试听内容<textarea data-id="workText" maxlength="1000">梨梨，今天也一起听听我们的声音吧。</textarea></label><label data-id="workModelLabel">试听模型<select data-id="workModel"><option>speech-2.8-hd</option><option>speech-2.8-turbo</option><option>speech-2.6-hd</option><option>speech-2.6-turbo</option></select></label><p class="lv-work-note">生成试听会计费；播放已有试听不重复计费。新音色需在 7 天内正式配音才会保留，首次正式使用另有音色费用。</p><div class="lv-row"><button data-id="createVoice" type="button" class="lv-primary">克隆并生成试听</button><button data-id="cancelWork" type="button" hidden>取消请求</button></div><p data-id="workStatus" role="status"></p><audio data-id="workAudio" controls hidden></audio><h3>我的创作音色</h3><div data-id="createdVoices"></div>`;
 q('configPage').before(page);
 const tab=el('button','工作台');tab.type='button';tab.dataset.id='tabWorkbench';tab.id='lv-tab-workbench';tab.setAttribute('role','tab');tab.setAttribute('aria-controls',page.id);tab.setAttribute('aria-selected','false');q('tabConfig').before(tab);
 const existingTabs=[...dialog.querySelectorAll('.lv-tabs button')].filter(b=>b!==tab);
 function closeWork(){page.hidden=true;tab.setAttribute('aria-selected','false');}
 existingTabs.forEach(button=>button.addEventListener('click',closeWork));
 tab.onclick=()=>{for(const panel of dialog.querySelectorAll('.lv-page'))panel.hidden=panel!==page;for(const button of existingTabs)button.setAttribute('aria-selected','false');tab.setAttribute('aria-selected','true');refreshProfile();renderCreated();};
 const oldBack=window.PearVoice.back;window.PearVoice.back=()=>{if(!page.hidden){closeWork();core.showTab('read');return true;}return oldBack();};
 const links=el('div',null,'lv-account-links');const recharge=el('a','MiniMax 充值');recharge.href='https://platform.minimax.cn/console/recharge-records';recharge.rel='noopener noreferrer';links.append(recharge);q('configPage').append(links);
 let mode='clone',controller=null,workToken=0,sampleUrl='',trialUrl='',lastProfile='',badgeToken=0,accountBusy=false,balanceBusy=false;
 const workStatus=text=>{q('workStatus').textContent=text;};
 const keyOf=async profile=>{const data=new TextEncoder().encode([profile.id,profile.host,profile.groupId||'',profile.key||''].join('\n'));return [...new Uint8Array(await crypto.subtle.digest('SHA-256',data))].map(v=>v.toString(16).padStart(2,'0')).join('');};
 let balanceCache={};try{balanceCache=JSON.parse(localStorage.getItem('lili-voice-official-balances')||'{}');}catch{}
 async function renderBalance(){const profile=core.profile(),token=++badgeToken;if(!profile){balance.textContent='余额 · 配置';balance.title='请先保存 MiniMax 接口';return;}if(profile.host.includes('.io')){balance.textContent='余额 · 官网';balance.title='国际站请在官网查看';return;}const key=await keyOf(profile);if(token!==badgeToken)return;const item=balanceCache[key];balance.textContent=item?`¥${Number(item.balance).toFixed(2)} · ${item.stale?'上次':'官网'}`:'余额 · 登录';balance.title=item?`官网账户 ${item.groupId} · ${new Date(item.updatedAt).toLocaleString()}\n点击查看消费明细；可重新同步余额。`:'登录官网后同步余额并查看消费明细';}
 balance.onclick=async()=>{if(accountBusy)return;const profile=core.profile();if(!profile)return core.status('请先保存并选择 MiniMax 接口。');if(profile.host.includes('.io')){location.href='https://platform.minimax.io/console/recharge-records';return;}if(!window.PearAndroid?.account)return core.status('此功能需安装新版 APK。');accountBusy=true;balance.disabled=true;try{const key=await keyOf(profile);const result=await window.pearAccount({profileName:profile.name,groupId:profile.groupId||'',history:!!balanceCache[key]});if(result.account){balanceCache[key]=result.account;localStorage.setItem('lili-voice-official-balances',JSON.stringify(balanceCache));core.status('官网余额已同步。点击右上角查看消费明细。');}await renderBalance();}catch(error){core.status(core.safe(error.message));}finally{accountBusy=false;balance.disabled=false;}};
 async function refreshOfficialBalance(){if(balanceBusy||accountBusy||!window.PearAndroid?.balance)return;const profile=core.profile();if(!profile||profile.host.includes('.io'))return;const key=await keyOf(profile),old=balanceCache[key];if(!old?.groupId)return;balanceBusy=true;try{const result=await window.pearBalance({groupId:old.groupId});balanceCache[key]=result;localStorage.setItem('lili-voice-official-balances',JSON.stringify(balanceCache));}catch{balanceCache[key]={...old,stale:true};}finally{balanceBusy=false;renderBalance();}}
 window.addEventListener('pear-minimax-used',()=>setTimeout(refreshOfficialBalance,1500));window.addEventListener('focus',refreshOfficialBalance);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshOfficialBalance();});
 function refreshProfile(){const p=core.profile();q('workProfile').textContent=p?'当前接口：'+p.name:'先在配置页保存 MiniMax 接口';const signature=p?JSON.stringify([p.id,p.host,p.groupId,p.key]):'';if(signature!==lastProfile){lastProfile=signature;renderBalance();refreshOfficialBalance();if(!page.hidden)renderCreated();}}
 const ticker=setInterval(refreshProfile,1200);refreshProfile();renderBalance();
 function changeMode(next){mode=next;q('cloneFields').hidden=mode!=='clone';q('designFields').hidden=mode!=='design';q('modeClone').setAttribute('aria-selected',String(mode==='clone'));q('modeDesign').setAttribute('aria-selected',String(mode==='design'));q('workModelLabel').hidden=mode==='design';q('workText').maxLength=mode==='design'?500:1000;q('createVoice').textContent=mode==='clone'?'克隆并生成试听':'生成音色与试听';}
 q('modeClone').onclick=()=>changeMode('clone');q('modeDesign').onclick=()=>changeMode('design');
 q('cloneFile').onchange=()=>{if(sampleUrl)URL.revokeObjectURL(sampleUrl);const file=q('cloneFile').files[0];q('sampleAudio').hidden=!file;if(file){sampleUrl=URL.createObjectURL(file);q('sampleAudio').src=sampleUrl;}else{sampleUrl='';q('sampleAudio').removeAttribute('src');}};
 function stopTrial(){q('workAudio').pause();q('workAudio').removeAttribute('src');q('workAudio').hidden=true;if(trialUrl)URL.revokeObjectURL(trialUrl);trialUrl='';}
 async function playBlob(blob){core.stopAll();q('sampleAudio').pause();stopTrial();trialUrl=URL.createObjectURL(blob);q('workAudio').src=trialUrl;q('workAudio').hidden=false;try{await q('workAudio').play();}catch{workStatus('请点击播放器试听。');}}
 dialog.addEventListener('play',event=>{for(const audio of dialog.querySelectorAll('audio'))if(audio!==event.target)audio.pause();},true);
 function checked(data,response){if(!response.ok||data.base_resp?.status_code!==0){const code=data.base_resp?.status_code??response.status;throw Error('MiniMax '+code+'：'+(data.base_resp?.status_msg||'请求未成功'));}return data;}
 async function api(profile,path,body,signal){const url=new URL(path,profile.host);if(profile.groupId)url.searchParams.set('GroupId',profile.groupId);const multipart=body instanceof FormData;const encoded=multipart?body:JSON.stringify(body).replace(/("(?:file_id|prompt_audio)"\s*:\s*)"(\d+)"/g,'$1$2');const response=await window.pearFetch(url.href,{method:'POST',headers:{Authorization:'Bearer '+profile.key,...(multipart?{}:{'Content-Type':'application/json'})},body:encoded,signal});const text=await response.text();let data;try{data=JSON.parse(text.replace(/("file_id"\s*:\s*)(\d+)/g,'$1"$2"'));}catch{throw Error('MiniMax HTTP '+response.status+'：未返回有效结果。');}return checked(data,response);}
 async function duration(file,signal){return new Promise((resolve,reject)=>{const audio=new Audio(),url=URL.createObjectURL(file);let done=false;const timer=setTimeout(()=>finish(Error('无法读取音频时长，请转换为 MP3 或 WAV 后重试。')),15000);const abort=()=>finish(new DOMException('Aborted','AbortError'));function finish(error,value){if(done)return;done=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);audio.removeAttribute('src');audio.load();URL.revokeObjectURL(url);error?reject(error):resolve(value);}audio.onloadedmetadata=()=>Number.isFinite(audio.duration)?finish(null,audio.duration):finish(Error('音频时长无效。'));audio.onerror=()=>finish(Error('无法解码音频，请转换为 MP3 或 WAV。'));signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)return abort();audio.preload='metadata';audio.src=url;});}
 async function validateFile(file,prompt,signal){if(!file)throw Error('请选择参考音频。');if(!/\.(mp3|m4a|wav)$/i.test(file.name))throw Error('只支持 MP3、M4A、WAV。');if(!file.size||file.size>20*1024*1024)throw Error('音频须大于 0 且不超过 20 MB。');const seconds=await duration(file,signal);if(prompt?seconds<=0||seconds>=8:seconds<10||seconds>300)throw Error(prompt?'辅助音频必须小于 8 秒。':'参考音频需为 10 秒至 5 分钟。');}
 async function upload(profile,file,purpose,signal){const form=new FormData();form.append('purpose',purpose);form.append('file',file,file.name);const result=await api(profile,'/v1/files/upload',form,signal);const id=String(result.file?.file_id||'');if(!/^\d+$/.test(id))throw Error('上传结果没有有效 file_id。');return id;}
 function hexBlob(hex){if(typeof hex!=='string'||!hex.length||hex.length%2||hex.length>128*1024*1024||!/^[a-f\d]+$/i.test(hex))throw Error('试听音频数据无效。');const bytes=new Uint8Array(hex.length/2);for(let i=0;i<bytes.length;i++)bytes[i]=parseInt(hex.slice(i*2,i*2+2),16);return new Blob([bytes],{type:'audio/mpeg'});}
 async function demoBlob(url,signal){let target=new URL(url);if(target.protocol!=='https:'||target.username||target.password)throw Error('试听下载地址无效。');const response=await window.pearFetch(target.href,{signal});if(!response.ok)throw Error('试听下载失败：HTTP '+response.status);const blob=await response.blob();if(!blob.size||blob.size>64*1024*1024)throw Error('试听音频大小无效。');return new Blob([blob],{type:'audio/mpeg'});}
 async function persistPreview(voice,profile,blob,text,model){const row=await core.savePreview(blob,{host:profile.host,model,language:'auto'},voice,text);voice.previewHistoryId=row.id;core.saveVoice(voice);return row;}
 q('cancelWork').onclick=()=>{controller?.abort();workStatus('已取消等待；已提交的请求可能仍会执行，请先检查结果，不要重复创建。');};
 q('createVoice').onclick=async()=>{
 if(controller||core.busy())return workStatus('请先等待当前请求结束。');const profile=core.profile();if(!profile?.key)return workStatus('请先在配置页保存 MiniMax API Key。');const name=q('workName').value.trim(),text=q('workText').value.trim(),description=q('voiceDescription').value.trim(),selectedMode=mode,model=q('workModel').value;const voiceId=q('workVoiceId').value.trim()||'Pear'+crypto.randomUUID().replace(/-/g,'');
 if(!name)return workStatus('请填写音色名称。');if(!/^[A-Za-z][A-Za-z\d_-]{6,254}[A-Za-z\d]$/.test(voiceId))return workStatus('Voice ID 需为 8–256 位，以字母开头、字母或数字结尾，只能含字母、数字、-、_。');if(!text||[...text].length>(mode==='design'?500:1000))return workStatus(mode==='design'?'试听内容需为 1–500 字符。':'试听内容需为 1–1000 字符。');if(mode==='design'&&!description)return workStatus('请填写声音描述。');if(core.voices().some(v=>v.voiceId===voiceId&&v.sourceProfileId===profile.id))return workStatus('这个 Voice ID 已存在，请换一个。');
 const reference=q('cloneFile').files[0],promptFile=q('promptFile').files[0],promptText=q('promptText').value.trim(),denoise=q('denoise').checked,normalize=q('normalize').checked;
 q('workVoiceId').value=voiceId;const ctrl=new AbortController(),token=++workToken;controller=ctrl;const timer=setTimeout(()=>ctrl.abort(),180000);const controls=[...page.querySelectorAll('button,input,select,textarea')].filter(e=>!e.disabled);controls.forEach(e=>e.disabled=true);core.setBusy(true);q('cancelWork').hidden=false;q('cancelWork').disabled=false;let voice=null;
 try{
 let result;if(selectedMode==='clone'){workStatus('正在检查参考音频…');await validateFile(reference,false,ctrl.signal);if(promptFile){if(!promptText)throw Error('请填写辅助音频原文。');await validateFile(promptFile,true,ctrl.signal);}workStatus('正在上传参考音频…');const fileId=await upload(profile,reference,'voice_clone',ctrl.signal);const body={file_id:fileId,voice_id:voiceId,text,model,need_noise_reduction:denoise,need_volume_normalization:normalize};if(promptFile)body.clone_prompt={prompt_audio:await upload(profile,promptFile,'prompt_audio',ctrl.signal),prompt_text:promptText};workStatus('正在克隆并生成试听…');result=await api(profile,'/v1/voice_clone',body,ctrl.signal);if(result.input_sensitive===true||result.input_sensitive?.is_sensitive)throw Error('参考音频未通过平台检查。');}else{workStatus('正在生成音色与试听…');result=await api(profile,'/v1/voice_design',{prompt:description,preview_text:text,voice_id:voiceId},ctrl.signal);}
 const actualId=String(result.voice_id||voiceId);voice={id:crypto.randomUUID(),name,voiceId:actualId,speed:1,volume:1,pitch:0,source:selectedMode,sourceProfileId:profile.id,sourceHost:profile.host,createdAt:Date.now(),demoUrl:selectedMode==='clone'?result.demo_audio||'':'',previewText:text,previewModel:selectedMode==='clone'?model:'voice_design'};core.saveVoice(voice);q('workVoiceId').value='';q('cloneFile').value='';q('promptFile').value='';if(sampleUrl){URL.revokeObjectURL(sampleUrl);sampleUrl='';q('sampleAudio').removeAttribute('src');q('sampleAudio').hidden=true;}renderCreated();
 const blob=selectedMode==='clone'?await demoBlob(result.demo_audio,ctrl.signal):hexBlob(result.trial_audio);if(token!==workToken)return;await playBlob(blob);await persistPreview(voice,profile,blob,text,voice.previewModel);workStatus('音色已加入音色列表，试听已保存到“存储”。');renderCreated();
 }catch(error){workStatus((voice?'音色 '+voice.voiceId+' 已创建；试听尚未保存：':'')+(error.name==='AbortError'?'请求已停止等待，请先在官网确认结果后重试。':core.safe(error.message)));}
 finally{clearTimeout(timer);if(token===workToken){controller=null;controls.forEach(e=>e.disabled=false);core.setBusy(false);q('cancelWork').hidden=true;}}
 };
 function renderCreated(){const list=q('createdVoices'),profile=core.profile();list.replaceChildren();const voices=core.voices().filter(v=>v.source&&v.sourceProfileId===profile?.id).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));for(const voice of voices){const card=el('details',null,'lv-record');const summary=el('summary',voice.name);card.append(summary,el('p',`${voice.source==='clone'?'克隆':'生成'} · ${voice.voiceId}`));const row=el('div',null,'lv-row');const button=(label,fn)=>{const b=el('button',label);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(error){workStatus(core.safe(error.message));}finally{b.disabled=false;}};row.append(b);};if(voice.previewHistoryId)button('播放试听',async()=>playBlob(await core.historyBlob(voice.previewHistoryId)));else if(voice.demoUrl)button('加载已有试听',async()=>{const blob=await demoBlob(voice.demoUrl);await persistPreview(voice,profile,blob,voice.previewText,voice.previewModel);await playBlob(blob);renderCreated();});button('去配音',()=>{if(controller)throw Error('请先结束工作台请求。');core.useVoice(voice.id);closeWork();core.status('已选用新音色。首次正式配音可能收取音色费用，请确认后生成。');});if(voice.previewHistoryId)button('下载试听',async()=>core.saveFile(await core.historyBlob(voice.previewHistoryId),voice.name.replace(/[\\/:*?"<>|]/g,'_')+'-试听.mp3'));card.append(row);list.append(card);}if(!voices.length)list.append(el('p','这个接口还没有在工作台创建的音色。'));}
 window.addEventListener('pagehide',event=>{if(event.persisted)return;clearInterval(ticker);controller?.abort();stopTrial();if(sampleUrl)URL.revokeObjectURL(sampleUrl);},{once:true});
 };
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
