package net.pearvoice.app;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.webkit.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;
public class AccountActivity extends Activity {
 private WebView browser;private TextView message;private Button sync;private final Handler handler=new Handler();private String queryScript;private JSONObject latest;private int generation=0;private boolean dead=false;
 private static final String BASE="https://platform.minimax.cn";
 private boolean official(Uri u){String h=u.getHost();return "https".equals(u.getScheme())&&("platform.minimax.cn".equals(h)||"platform.minimaxi.com".equals(h)||"account.minimax.cn".equals(h)||"account.minimaxi.com".equals(h)||"www.minimax.cn".equals(h));}
 public void onCreate(Bundle state){super.onCreate(state);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(Color.WHITE);setContentView(root);root.setOnApplyWindowInsetsListener((v,in)->{if(Build.VERSION.SDK_INT>=30){android.graphics.Insets i=in.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.ime());v.setPadding(i.left,i.top,i.right,i.bottom);}else v.setPadding(in.getSystemWindowInsetLeft(),in.getSystemWindowInsetTop(),in.getSystemWindowInsetRight(),in.getSystemWindowInsetBottom());return in;});root.requestApplyInsets();LinearLayout bar=new LinearLayout(this);root.addView(bar,new LinearLayout.LayoutParams(-1,-2));Button back=new Button(this);back.setText("返回");bar.addView(back);back.setOnClickListener(v->finishAccount());Button balance=new Button(this);balance.setText("余额");bar.addView(balance);balance.setOnClickListener(v->browser.loadUrl(BASE+"/console/recharge-records"));Button history=new Button(this);history.setText("明细");bar.addView(history);history.setOnClickListener(v->browser.loadUrl(BASE+"/console/consumption-detail"));sync=new Button(this);sync.setText("同步余额");bar.addView(sync,new LinearLayout.LayoutParams(0,-2,1));sync.setOnClickListener(v->syncBalance());message=new TextView(this);message.setTextSize(12);message.setPadding(16,6,16,10);message.setText("请登录接口「"+getIntent().getStringExtra("profileName")+"」对应的官网账户，再点同步余额。");root.addView(message);browser=new WebView(this);root.addView(browser,new LinearLayout.LayoutParams(-1,0,1));WebSettings settings=browser.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setAllowFileAccess(false);settings.setAllowContentAccess(false);settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(browser,true);browser.setWebChromeClient(new WebChromeClient());browser.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest request){Uri uri=request.getUrl();if(!request.isForMainFrame())return !"https".equals(uri.getScheme());if(official(uri))return false;if(request.isForMainFrame()&&"https".equals(uri.getScheme()))try{startActivity(new Intent(Intent.ACTION_VIEW,uri));}catch(Exception ignored){}return true;}});try(InputStream in=getAssets().open("web/account-query.js")){ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)out.write(b,0,n);queryScript=out.toString("UTF-8");}catch(Exception e){sync.setEnabled(false);message.setText("账户查询组件未能加载。");}browser.loadUrl(BASE+(getIntent().getBooleanExtra("history",false)?"/console/consumption-detail":"/console/recharge-records"));}
 private void syncBalance(){if(browser.getUrl()==null||!official(Uri.parse(browser.getUrl()))){message.setText("请先回到 MiniMax 官网。");return;}sync.setEnabled(false);message.setText("正在读取官网余额…");int token=++generation;String expected=getIntent().getStringExtra("groupId");browser.evaluateJavascript("window.__pearAccountTicket="+token+";window.__pearExpectedGroup="+JSONObject.quote(expected==null?"":expected)+";"+queryScript,null);poll(token,0);}
 private void poll(int token,int count){handler.postDelayed(()->{if(dead||token!=generation)return;if(count>60){sync.setEnabled(true);message.setText("查询超时，请先完成登录再重试。");return;}if(browser.getUrl()==null||!official(Uri.parse(browser.getUrl()))){sync.setEnabled(true);message.setText("请在官网控制台同步余额。");return;}browser.evaluateJavascript("JSON.stringify(window.__pearAccountSync||null)",value->{if(dead||token!=generation)return;try{Object decoded=new JSONTokener(value).nextValue();JSONObject result=decoded instanceof String?new JSONObject((String)decoded):null;if(result==null||result.optInt("ticket",-1)!=token||result.optBoolean("pending",false)){poll(token,count+1);return;}sync.setEnabled(true);if(result.has("error")){message.setText(result.optString("error"));return;}String amount=result.getString("balance");if(!amount.matches("-?[0-9]+(\\.[0-9]+)?")||amount.length()>50)throw new Exception();latest=new JSONObject();latest.put("balance",amount);latest.put("currency","CNY");latest.put("groupId",result.optString("groupId"));latest.put("updatedAt",System.currentTimeMillis());message.setText("已同步 ¥"+amount+" · 账户 "+latest.optString("groupId")+"，返回后显示。");CookieManager.getInstance().flush();}catch(Exception e){sync.setEnabled(true);message.setText("暂未读取到余额，请完成官网登录后重试。");}});},250);}
 private void finishAccount(){Intent data=new Intent();if(latest!=null)data.putExtra("balance",latest.toString());setResult(RESULT_OK,data);finish();}
 @Override public void onBackPressed(){finishAccount();}
 protected void onDestroy(){dead=true;generation++;handler.removeCallbacksAndMessages(null);if(browser!=null){browser.destroy();browser=null;}super.onDestroy();}
}
